window.SEED_PERSONAL = [
  {
    "nombre": "Arnaldo Andrade",
    "jerarquia": "ALC MYR (E.G)",
    "servicio": "6hs",
    "dias": "MIERCOLES A DOMINGO",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES (ROTATIVO)",
    "estado": "Inactivo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES A DOMINGO",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES (ROTATIVO)"
      },
      {
        "dias": "MIERCOLES A DOMINGO",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 19",
        "observaciones": "RESTRICCIONES (ROTATIVO)"
      }
    ]
  },
  {
    "nombre": "Avilez Claudio",
    "jerarquia": "SUBOF. PPAL. (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES\nSABADO Y DOMINGO",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": ""
      },
      {
        "dias": "SABADO Y DOMINGO",
        "hora_inicio": "",
        "hora_fin": "",
        "servicio": "24hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "48 HS",
        "observaciones": ""
      }
    ],
    "legajo": "349.585",
    "situacion": ""
  },
  {
    "nombre": "Barrera Hugo",
    "jerarquia": "CABO (E.G)",
    "servicio": "Diario",
    "dias": "MARTES, JUEVES Y SABADO",
    "hora_inicio": "07",
    "hora_fin": "17",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MARTES, JUEVES Y SABADO",
        "hora_inicio": "07",
        "hora_fin": "17",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 17",
        "observaciones": "RESTRICCIONES"
      }
    ]
  },
  {
    "nombre": "Carranza Gustavo",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "Diario",
    "dias": "DOM O SAB, LUNES Y MIERCOLES",
    "hora_inicio": "07",
    "hora_fin": "17",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "DOM O SAB, LUNES Y MIERCOLES",
        "hora_inicio": "07",
        "hora_fin": "17",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 17",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Casaus Coria Cesar Oscar",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "Diario",
    "dias": "MIERCOLES A DOMINGO",
    "hora_inicio": "22",
    "hora_fin": "05",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "TODO EL MES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES A DOMINGO",
        "hora_inicio": "22",
        "hora_fin": "05",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "22 A 05",
        "observaciones": "TODO EL MES"
      }
    ],
    "legajo": "329.648",
    "situacion": ""
  },
  {
    "nombre": "Cepeda Miguel",
    "jerarquia": "SGTO. 1º (E.G.)",
    "servicio": "6hs",
    "dias": "MIERCOLES Y VIERNES\nMARTES, JUEVES Y SABADO",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES Y VIERNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "MARTES, JUEVES Y SABADO",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "670.522",
    "situacion": ""
  },
  {
    "nombre": "Clarisa Reyna",
    "jerarquia": "ADJUTOR (E.G.)",
    "servicio": "4hs",
    "dias": "MIERCOLES A DOMINGO",
    "hora_inicio": "19",
    "hora_fin": "23",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "MATERNIDAD",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES A DOMINGO",
        "hora_inicio": "19",
        "hora_fin": "23",
        "servicio": "4hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "19 A 23",
        "observaciones": "MATERNIDAD"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Cristina Ayala",
    "jerarquia": "ALCAIDE (E.ADM)",
    "servicio": "Diario",
    "dias": "MIERCOLES A DOMINGO",
    "hora_inicio": "14",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "",
    "estado": "Inactivo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES A DOMINGO",
        "hora_inicio": "14",
        "hora_fin": "19",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "14 A 19",
        "observaciones": ""
      }
    ]
  },
  {
    "nombre": "Daiana Gonzalez",
    "jerarquia": "SGTO. AYTE. (E.G.)",
    "servicio": "Diario",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "20",
    "hora_fin": "03",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "20",
        "hora_fin": "03",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "20 A 03",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Delgado Luciana",
    "jerarquia": "ADJUTOR (E.G.)",
    "servicio": "Diario",
    "dias": "JUEVES Y DOMINGO",
    "hora_inicio": "12",
    "hora_fin": "22",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "MATERNIDAD",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "JUEVES Y DOMINGO",
        "hora_inicio": "12",
        "hora_fin": "22",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "12:00 A 22:00",
        "observaciones": "MATERNIDAD"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Diaz Walter",
    "jerarquia": "CABO",
    "servicio": "Diario",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "07",
    "hora_fin": "12",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "07",
        "hora_fin": "12",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07:00 A 12:00",
        "observaciones": "RESTRICCIONES"
      }
    ]
  },
  {
    "nombre": "Fernandez Maria Sol",
    "jerarquia": "SGTO. 1º (E.G.)",
    "servicio": "Diario",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "07",
    "hora_fin": "12",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "07",
        "hora_fin": "12",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 12",
        "observaciones": "RESTRICCIONES"
      }
    ]
  },
  {
    "nombre": "Fernandez Raul Sebastian",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "Diario",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "13",
    "hora_fin": "21",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "13",
        "hora_fin": "21",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 21",
        "observaciones": ""
      }
    ],
    "legajo": "607.905",
    "situacion": ""
  },
  {
    "nombre": "Freda Gaston",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES, MIERCOLES Y VIERNES\nMARTES Y JUEVES",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES, MIERCOLES Y VIERNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07:00 A 13:00",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "MARTES Y JUEVES",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13:00 A 19:00",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Gallardo Gaston",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "6hs",
    "dias": "MARTES A SABADOS",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MARTES A SABADOS",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "607.940",
    "situacion": ""
  },
  {
    "nombre": "Gaston Moreira",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "12hs",
    "dias": "MARTES, JUEVES Y DOMINGO",
    "hora_inicio": "07",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MARTES, JUEVES Y DOMINGO",
        "hora_inicio": "07",
        "hora_fin": "19",
        "servicio": "12hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Gregorio Monica Beatriz",
    "jerarquia": "SUBOF. PPAL. (E.G.)",
    "servicio": "24hs",
    "dias": "SABADO\nDOMINGO\nLUNES",
    "hora_inicio": "",
    "hora_fin": "",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "SABADO",
        "hora_inicio": "",
        "hora_fin": "",
        "servicio": "24hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "24 HRS",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "DOMINGO",
        "hora_inicio": "07",
        "hora_fin": "11",
        "servicio": "4hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 11",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "LUNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "348.381",
    "situacion": ""
  },
  {
    "nombre": "Jadech Amira",
    "jerarquia": "ADJUTOR (E.G.)",
    "servicio": "4hs",
    "dias": "DOMINGO A JUEVES",
    "hora_inicio": "19",
    "hora_fin": "23",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "MATERNIDAD",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "DOMINGO A JUEVES",
        "hora_inicio": "19",
        "hora_fin": "23",
        "servicio": "4hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "19 A 23",
        "observaciones": "MATERNIDAD"
      }
    ],
    "legajo": "667.055",
    "situacion": ""
  },
  {
    "nombre": "Lastra Cesar Maximiliano",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "20",
    "hora_fin": "02",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "PUESTO 1",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "20",
        "hora_fin": "02",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "20 A 02",
        "observaciones": "PUESTO 1"
      }
    ]
  },
  {
    "nombre": "Lovelli Georgina",
    "jerarquia": "ADJUTOR (E.G.)",
    "servicio": "6hs",
    "dias": "MARTES Y VIERNES\nSABADO",
    "hora_inicio": "15",
    "hora_fin": "21",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "MATERNIDAD",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MARTES Y VIERNES",
        "hora_inicio": "15",
        "hora_fin": "21",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "15 A 21",
        "observaciones": "MATERNIDAD"
      },
      {
        "dias": "SABADO",
        "hora_inicio": "15",
        "hora_fin": "23",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "15 A 23",
        "observaciones": "MATERNIDAD"
      }
    ],
    "legajo": "670.868",
    "situacion": ""
  },
  {
    "nombre": "Martin Rebollo",
    "jerarquia": "SGTO. AYTE. (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "13",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "357.967",
    "situacion": ""
  },
  {
    "nombre": "Mire Franco",
    "jerarquia": "SUBALCAIDE (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES A JUEVES\nDOMINGO",
    "hora_inicio": "13",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A JUEVES",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13:00 A 19:00",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "DOMINGO",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07:00 A 13:00",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "663.867",
    "situacion": ""
  },
  {
    "nombre": "Natalia Magallanes",
    "jerarquia": "PPAL. (E.G.)",
    "servicio": "Diario",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "07",
    "hora_fin": "14",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "SERVICIO",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "07",
        "hora_fin": "14",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 14",
        "observaciones": "SERVICIO"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Paulo Correas",
    "jerarquia": "ALCAIDE (E.G.)",
    "servicio": "12hs",
    "dias": "LUNES Y SAB O DOM\nJUEVES",
    "hora_inicio": "07",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES Y SAB O DOM",
        "hora_inicio": "07",
        "hora_fin": "19",
        "servicio": "12hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 19",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "JUEVES",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Perez Vanessa Laura",
    "jerarquia": "SGTO. AYTE. (E.G.)",
    "servicio": "Diario",
    "dias": "MARTES A SABADO",
    "hora_inicio": "07",
    "hora_fin": "14",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MARTES A SABADO",
        "hora_inicio": "07",
        "hora_fin": "14",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 14",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "352.312",
    "situacion": "ART"
  },
  {
    "nombre": "Poblete Carolina Maria Janete",
    "jerarquia": "ALC. MYR. (E.G.)",
    "servicio": "4hs",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "19",
    "hora_fin": "23",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "MATERNIDAD",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "19",
        "hora_fin": "23",
        "servicio": "4hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "19 A 23",
        "observaciones": "MATERNIDAD"
      }
    ],
    "legajo": "367.299",
    "situacion": ""
  },
  {
    "nombre": "Quattrini Lucas",
    "jerarquia": "SARGENTO (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES, MIERCOLES Y VIERNES\nMARTES Y JUEVES",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES, MIERCOLES Y VIERNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "MARTES Y JUEVES",
        "hora_inicio": "13",
        "hora_fin": "19",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "620.481",
    "situacion": ""
  },
  {
    "nombre": "Rafael Leiva",
    "jerarquia": "SGTO. AYTE. (E.G.)",
    "servicio": "12hs",
    "dias": "LUNES Y MIERCOLES\nSABADO O DOMINGO (ROTATIVO)",
    "hora_inicio": "07",
    "hora_fin": "19",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES Y MIERCOLES",
        "hora_inicio": "07",
        "hora_fin": "19",
        "servicio": "12hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07 A 19",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "SABADO O DOMINGO (ROTATIVO)",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "2026-07-06",
        "texto_horario": "07 A 13",
        "observaciones": "RESTRICCIONES",
        "dias_rotativos": true
      }
    ],
    "legajo": "",
    "situacion": ""
  },
  {
    "nombre": "Riveros Laura",
    "jerarquia": "CABO 1 (E.G)",
    "servicio": "4hs",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "14",
    "hora_fin": "18",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "14",
        "hora_fin": "18",
        "servicio": "4hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "14 A 18",
        "observaciones": "RESTRICCIONES"
      }
    ]
  },
  {
    "nombre": "Sala Claudio Dario",
    "jerarquia": "SUBOF. MYR. (E.G.)",
    "servicio": "12hs",
    "dias": "LUNES, MARTES Y JUEVES",
    "hora_inicio": "13",
    "hora_fin": "01",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES, MARTES Y JUEVES",
        "hora_inicio": "13",
        "hora_fin": "01",
        "servicio": "12hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "13 A 01",
        "observaciones": ""
      }
    ],
    "legajo": "358.349",
    "situacion": ""
  },
  {
    "nombre": "Segovia Federico",
    "jerarquia": "ALCAIDE (E.G.)",
    "servicio": "6hs",
    "dias": "LUNES A VIERNES (ROTATIVO)\nSABADO (ROTATIVO)",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Rotativo semanal",
    "rotativo_a_inicio": "07",
    "rotativo_a_fin": "13",
    "rotativo_b_inicio": "13",
    "rotativo_b_fin": "19",
    "fecha_base_rotacion": "06/07/2026",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Rotativo semanal",
        "rotativo_a_inicio": "07",
        "rotativo_a_fin": "13",
        "rotativo_b_inicio": "13",
        "rotativo_b_fin": "19",
        "fecha_base_rotacion": "06/07/2026",
        "texto_horario": "07 A 13 / 13 A 19",
        "observaciones": "RESTRICCIONES"
      },
      {
        "dias": "SABADO",
        "hora_inicio": "07",
        "hora_fin": "12",
        "servicio": "Diario",
        "modalidad": "Rotativo semanal",
        "rotativo_a_inicio": "07",
        "rotativo_a_fin": "12",
        "rotativo_b_inicio": "14",
        "rotativo_b_fin": "19",
        "fecha_base_rotacion": "06/07/2026",
        "texto_horario": "07 A 12 / 14 A 19",
        "observaciones": "RESTRICCIONES"
      }
    ],
    "legajo": "658.455",
    "situacion": ""
  },
  {
    "nombre": "Valdez Carmen",
    "jerarquia": "SUBALCAIDE (E.ADM)",
    "servicio": "6hs",
    "dias": "LUNES A VIERNES",
    "hora_inicio": "07",
    "hora_fin": "13",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "RESTRICCIONES",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "LUNES A VIERNES",
        "hora_inicio": "07",
        "hora_fin": "13",
        "servicio": "6hs",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "07:00 A 13:00",
        "observaciones": "RESTRICCIONES"
      }
    ]
  },
  {
    "nombre": "Zalazar Fabian Alejandro",
    "jerarquia": "SGTO. AYTE. (E.G.)",
    "servicio": "Diario",
    "dias": "MIERCOLES, VIERNES Y SABADO",
    "hora_inicio": "21",
    "hora_fin": "07",
    "turno_24": "",
    "modalidad": "Fijo",
    "rotativo_a_inicio": "",
    "rotativo_a_fin": "",
    "rotativo_b_inicio": "",
    "rotativo_b_fin": "",
    "fecha_base_rotacion": "",
    "observaciones": "",
    "estado": "Activo",
    "ausencias": [],
    "asignaciones": [
      {
        "dias": "MIERCOLES, VIERNES Y SABADO",
        "hora_inicio": "21",
        "hora_fin": "07",
        "servicio": "Diario",
        "modalidad": "Fijo",
        "rotativo_a_inicio": "",
        "rotativo_a_fin": "",
        "rotativo_b_inicio": "",
        "rotativo_b_fin": "",
        "fecha_base_rotacion": "",
        "texto_horario": "21 A 07",
        "observaciones": ""
      }
    ],
    "legajo": "357.630",
    "situacion": ""
  }
];

window.SEED_TURNOS = {
  "turnos_24": {
    "A": [
      "Roberto Gerry"
    ],
    "B": [
      "Gaston Guglielmati",
      "Lautaro Cardona",
      "Sabrina Coria"
    ],
    "C": [
      "Yazmin Rodriguez",
      "Karina Calderon",
      "Eugenia Díaz",
      "Carlos Urquiza"
    ],
    "D": [
      "Andres Errecarte",
      "Carolina Godoy",
      "Eugenia Díaz",
      "Soria Oscar",
      "Juan Mallaina"
    ]
  },
  "canes_por_turno": {
    "A": "Marcelo Durany",
    "B": "Marcos Balbo",
    "C": "Matias Gutierrez",
    "D": "Cristian Mires"
  },
  "rotativos_48": [
    {
      "nombre": "Karina Calderon",
      "turnos": [
        "C",
        "D"
      ],
      "fecha_presente": "10/07/2026",
      "activo": true
    },
    {
      "nombre": "Eugenia Díaz",
      "turnos": [
        "C",
        "D"
      ],
      "fecha_presente": "10/07/2026",
      "activo": true
    },
    {
      "nombre": "Carolina Godoy",
      "turnos": [
        "C",
        "D"
      ],
      "fecha_presente": "14/07/2026",
      "activo": true
    }
  ]
};
